#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10
bspc config normal_border_color  "#2e3440"
bspc config focused_border_color "#4c566a"
bspc config top_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Gimp state=floating follow=on

feh --bg-max ~/Pictures/Wallpapers/100.png

 ~/.config/polybar/launch.sh
